name: Push to GCR GitHub Action
on: 
  push:
    branches:
      - main
      - prod

jobs:
  # example with gcloud service account key
  build-and-push-to-gcr-service-account:
    name: Build & push - with service account
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.B64_GCLOUD_SERVICE_ACCOUNT_JSON }}'
          path: main
      - name: Building and pushing the image
        #uses: ./
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta # <- use this on your workflow
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }} # <- not needed when used with google-github-actions/auth@v0
          registry: gcr.io
          project_id: mineonlium
          image_name: tea
          image_tag: tea-${{ github.sha }}, ${{ github.sha }}
          dockerfile: ./packages/backend/Dockerfile
          context: ./packages/backend/
          target: build
